[project]
name = "mcp_bridge"
version = "0.0.1"
requires-python = "==3.10.8"
dependencies = [
  "pip",
  "pydicom",
  "pyotp",
  "playwright"
]

# Explicitly declare the top-level modules
[tool.setuptools]
py-modules = ["parse_dicom_metadata", "rpa"]
