[project]
name = "platform"
version = "0.0.1"
requires-python = "==3.12.7"
dependencies = [
  "pip",
  "pydicom",
  "pyotp",
  "playwright"
]

# Explicitly declare the top-level modules
[tool.setuptools]
py-modules = ["parse_dicom_metadata", "rpa"]
